# Este é o arquivo config.toml corrigido e migrado.
# Ele contém apenas as configurações válidas do seu backup.

project_id = "yysnagznpvwgebjhgvzx"

[api]
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[studio]
api_url = "http://127.0.0.1:54321"

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://cvanalizer.fluxdata.com.br"
additional_redirect_urls = ["https://cvanalizer.fluxdata.com.br", "http://127.0.0.1:3000", "https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Confirme seu cadastro - CV Analyzer"
content_path = "./supabase/templates/confirmation.html"

#[auth.hook.send_email]
#enabled = true
#uri = "https://yysnagznpvwgebjhgvzx.supabase.co/functions/v1/send-email"
#secrets = {}

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.validate-card]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.resend-confirmation]
verify_jwt = true

[functions.start-trial]
verify_jwt = true
[functions.get-active-products]
enabled = true
verify_jwt = true
import_map = "./functions/get-active-products/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-active-products/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-active-products/*.html" ]

[functions.check-email-exists]
enabled = true
verify_jwt = true
import_map = "./functions/check-email-exists/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/check-email-exists/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/check-email-exists/*.html" ]
