// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yysnagznpvwgebjhgvzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5c25hZ3pucHZ3Z2Viamhndnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTc1MzIsImV4cCI6MjA3MjU3MzUzMn0.ApPFnOQZ3VKTPVwVlnqRXFrbL50miJ6qW5qXKt6VrSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});